### ISSUE TITLE
Tests not running

### ISSUE THREAD

**Issue by PMudra** [jesstelford/version-changelog#19]
I am trying to fix a bug with gitlab compare links. While setting up a fork I noticed that the tests wont work (on my machine?).

### Steps to reproduce

```
git clone git@github.com:jesstelford/version-changelog.git
cd version-changelog
npm install
npm run test
```

### Environment

- `node -v`: v10.16.0
- `npm -v`: 6.9.0
- `yarn -v`: 1.16.0
- `uname -opvrsi`: Linux 5.0.0-20-generic #21-Ubuntu SMP Mon Jun 24 09:32:09 UTC 2019 x86_64 x86_64 GNU/Linux

### Output (while running npm run test)

```
  Versioning Changelog (prefix source: "default")
    - Handles a non-git repo correctly
    1) Correctly adds a new version
    2) Correctly updates old unreleased sections
    3) Correctly handles empty Unreleased section
    4) Correctly skips old versions for links
    gitlab
      5) Correctly adds a new gitlab version
      6) Correctly updates old unreleased sections with gitlab urls
    bitbucket
      7) Correctly adds a new bitbucket version
      8) Correctly updates old unreleased sections with bitbucket urls


  0 passing (2s)
  1 pending
  8 failing

  1) Versioning Changelog (prefix source: "default")
       Correctly adds a new version:
     AssertionError [ERR_ASSERTION]: ifError got unwanted exception: '# Changelog\n\n## [Unreleased][]\n\n## [1.0.0][] - 2019-07-17\n- Foo\n\n[Unreleased]: https://github.com/jesstelford/version... == '# Changelog\n\n## [Unreleased][]\n\n## [1.0.0][] - 2019-07-17\n- Foo\n\n[Unreleased]: https://github.com/jesstelford/version...
      at /home/philipp/Documents/js/version/test/test.js:59:16
      at versionChangelog (index.js:166:5)
      at /home/philipp/Documents/js/version/test/test.js:60:16
      at versionChangelog (index.js:163:5)
      at Context.<anonymous> (test/test.js:47:5)

[...] all error messages look the same
```

I am almost certain the error is due to a missing 'v' version prefix in the actual result. But I cannot figure out what's wrong.

**Comment by PMudra** [comment]
Alright, I figured it out. My node installation was made using snap. When installing node the regular way everything is working fine. I believe this must be some kind of permission issue. That is spawning yarn from npm sandbox or something like that.
